### ISSUE TITLE
Feedback on Elastic Search Model README

### ISSUE THREAD

**Issue by eorodrig** [CMPUT301W15T13/TravelPlanner#137]
@aewilson-ua  Would you be able to provide feedback on this model?

Please read and provide feedback.
@lolicatgirls 
@mfritze 
@bkhunter 
@jihwan1ua 

This requires two folders in the server to seperate the objects: 
Claims
Expenses

Claims will have a UUID (a Universally Unique IDentifier). This will given at the time of creation of the claim (constructor). The odds of duplicate UUID is pretty low. The claim will be saved to that UUID on the server.
See: http://en.wikipedia.org/wiki/Universally_unique_identifier

When the user logs in, the claimlist will search for all the claims pertaining to the user that logged in.
The results will be saved to the claim list. 

Each expense will be saved on the server as its own object with its own unique ID (do not need UUID here). If we want to view an expense, we search to all the expenses objects which contain the claim ID (the UUID discussed previously). We save the results to the ExpenseList and display those results.

Any changes (updates,additions, deletions) will be saved to the server once they occur.

**Comment by lolicatgirls** [comment]
There are 2 links to information on UUID in the links page on the wiki
https://github.com/CMPUT301W15T13/TravelPlanner/wiki/Informational-Links

**Comment by aewilson-ua** [comment]
This design sounds good. Nitpick: what you called "folders" on the server are called "types" in elasticsearch terminology. Not a big deal, but keeping this in mind might help you with any documentation you need to read. By having Claims and Expenses as different types within the same index, you can do searches that can return both objects, which is kind of cool, by using http://softwareprocess.es/CMPUT301W15T13/_search as your search URL. if you do /claim/_search you will just get claims, and similarily /expense/_search would just search expenses.

You might want to consider using the [parent-child relationship that ES provides](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/parent-child.html), since it is basically along the lines of what you want to do already, but will give you a little extra power. For instance, you can then search for [claims by data in the expenses](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/has-child.html#has-child).

[Here is an article](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/nested-objects.html) discussing the problem that I mentioned with nested objects in ES in our meeting. It also provides another way to potentially adress this issue. What you are doing should work fine, but if you are finding it causes problems for you, you could always swithch to using the 'nested' mapping described there.

One thing to note is that [ES will generate uuids for you automatically](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-index_.html#_automatic_id_generation) which is pretty handy.
