### ISSUE TITLE
Adding android SDK 9 to the project 

### ISSUE THREAD

**Issue by mfritze** [CMPUT301W15T13/TravelPlanner#201]
@aewilson-ua

 The way I've set up maps requires android sdk 9, which cannot be installed on the lab machines since I do not have sufficient permission (but they work on my machine). What do you suggest to do to get around this?
Thanks

**Comment by aewilson-ua** [comment]
That's unfortunate. Your app really should run on the lab machines, and if you can't get Google maps to work there, then you shouldn't really be using it. Anyway, I won't make you change it because that would be a big pain. Here's what I want you to try:

### making it work

 * Make an AVD with google play services on the lab machines, with the most recent version available. Something with 4.2.2 or higher, I think.
 * Follow these steps on one of your personal computers: https://developer.android.com/google/play-services/setup.html so that you can copy the google-play-services library into your git repo, and reference that local version from eclipse. Here is a [stackoverflow q&A](http://stackoverflow.com/questions/14371725/add-google-play-services-to-eclipse-project) that might be helpful.

### if all else fails

If you can't make that work, then find and document a stable configuration for Eclipse. I want a wiki page that says what I need to install from the SDK manager, and what AVD settings I need to make sure that it will work. This is not ideal, but I don't want you to spend too much time on this kind of thing.

**Comment by mfritze** [comment]
Currently the google_play_services library is packaged with the app, found [here](https://github.com/CMPUT301W15T13/TravelPlanner/tree/maps/TravelPlanner/Additional%20resources/google-play-services_lib) . 

Without the SDK 9 though, the manifest breaks.

**Comment by aewilson-ua** [comment]
Can you elaborate on what you mean by SDK 9? Is that API level 9, i.e. Android 2.3? What do you mean by "the manifest breaks?" Can you provide an error message for that?

**Comment by mfritze** [comment]
Sorry, yes I mean API 9. 
The manifest includes this code:
    `<meta-data
        android:name="com.google.android.gms.version"
	android:value="@integer/google_play_services_version" />`

and  ` "@integer/google_play_services_version"` is from API 9.

The error message is `[2015-04-06 13:37:00 - google-play-services_lib] Unable to resolve target 'android-9'` and was resolved on my home computer by adding API 9 to Eclipse.

**Comment by aewilson-ua** [comment]
Okay, I downloaded this on my machine, where I do not have the API 9 SDK installed, and did the following things to make it work:

 1. move the google-play-services_lib folder so that it is next to the TravelPlanner and TravelPlannerTest projects
 3. import the google-play-services_lib project
 4. right-click TravelPlaner, select Properties, then Android. Make sure that you reference the google-play-services_lib project
 5. right-click google-play-services_lib in Package Explorer, select Android, and change the Project Build Target to Google APIs 17 or 19 or whatever you are using in the rest of your app.

Well, that fixed the build at least. I can't say for sure that everything works, but try this and report back.

**Comment by bkhunter** [comment]
Hey Alex, I am trying to implement this solution on the lab machines but am running into problems.

I can't find google-play-services_lib folder, but I can find a play-services folder which seems to have some stuff of use, however I can't import any of it. It seems like I don't have the right google play package.
I also found a bunch of folders with addon-google_apis-google-X where X is between 11 and 18, but importing this only gets me a 2 file sample maps app filled with errors.

I will try to search the internet for a solution, but any thoughts?

**Comment by aewilson-ua** [comment]
The google-play-services_lib folder is in [TravelPlanner/Additional resources/](https://github.com/CMPUT301W15T13/TravelPlanner/tree/maps/TravelPlanner/Additional%20resources/google-play-services_lib).

**Comment by aewilson-ua** [comment]
On the maps branch of your project

**Comment by mfritze** [comment]
So the bug was just that google play library was targeting API 9?

**Comment by bkhunter** [comment]
Give me one second

**Comment by bkhunter** [comment]
K I made the changes, but it didn't seem to make a difference...But I'm not on matt's branch, so I'll try that next.

**Comment by aewilson-ua** [comment]
@mfritze I think so. This other way of adding dependencies is also a bit more resilient, I think, so it may have fixed something as well.

@bkhunter if this doesn't work, then just give up, document the settings that do work, or the work-around, and add a ticket for future releases that you will get it working on the lab machines. Unless you need to do your work on the lab machine, that is.

**Comment by bkhunter** [comment]
The build was fixed, the app ran but I got this error:

04-07 03:23:53.122: E/dalvikvm(1920): Could not find class 'ca.ualberta.cmput301w15t13.Activities.GoogleMapActivity', referenced from method dialogs.ClaimantHomeLocationDialog$3.onClick
04-07 03:23:55.522: E/AndroidRuntime(1920): FATAL EXCEPTION: main
04-07 03:23:55.522: E/AndroidRuntime(1920): java.lang.NoClassDefFoundError: ca.ualberta.cmput301w15t13.Activities.GoogleMapActivity
04-07 03:23:55.522: E/AndroidRuntime(1920): 	at dialogs.ClaimantHomeLocationDialog$3.onClick(ClaimantHomeLocationDialog.java:84)

**Comment by bkhunter** [comment]
could this be a result of me missing something, or is it a dependency issue?

**Comment by mfritze** [comment]
Don't worry about that for now. It's an android manifest bug that I've fixed locally, I'll push... soon.

**Comment by bkhunter** [comment]
Oh so....did it work??

**Comment by mfritze** [comment]
I hope so haha. Try it again when the changes are pushed, I'm just adding soe more stuff to viewing maps.

**Comment by bkhunter** [comment]
kk no rush. There is hope if the project builds :+1:
