### ISSUE TITLE
Code Functionality: claims sorted by date

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#25]
User story:
[US02.02.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/55)

**Comment by eorodrig** [comment]
Done
Re-used the code from my project.

Approach:
Class implemented comparable <Class>    <-- this allows the class the ability to be comparable with the Collections API

To sort the list simply call the following method:
Collections.sort(List of Claims);

**Comment by eorodrig** [comment]
Just noticed the ClaimDateSort class has been implemented to tackle this sort.

Suggestion:
Class ClaimDateSort should be changed to Class DateSort
Change the type being sorted from Claim to a generic type  <T>

By doing this change we could use this class to sort claims and expenses with 1 class (instead of 2)

**Comment by lolicatgirls** [comment]
Reversed the sorting order, now shows most recent at top
