### ISSUE TITLE
Local persistance

### ISSUE THREAD

**Issue by bkhunter** [CMPUT301W15T13/TravelPlanner#27]
User story:
[US01.06.01](https://github.com/CMPUT301W15T13/TravelPlanner/issues/53)

**Comment by eorodrig** [comment]
Started working on this.

Will use generics to reduce code.

**Comment by eorodrig** [comment]
@bkhunter
@lolicatgirls 
@mfritze 
@jihwan1ua 

Network persistence kind of works now.
1. A claim is saved once it is created. (Check out the server to see the saved claims)
2. Only a claim creation is saved at this point. Need to discuss where the savepoints will be (And where in the code) with team on tuesday.
3. You can load claims from the network (kind of glitchy though...listener problem?)
In order to load a claim, you first must....
a. log in to the username that the claim was saved under.
b. press back/log out
c. log in again with the same user.
d. press the add new claim button.
e. press cancel...
f. all the saved claims show up :+1: 

Will need to get together with the team to address issues with 2 and 3.

**Comment by bkhunter** [comment]
Great work!!! :)

**Comment by eorodrig** [comment]
After some testing.. Issue 3 only occurs when the app is first opened.
After the app has been ran for a bit (switching between users, making new users etc),
you just need to:
a. log-in
b. press new claim
c. press cancel
d. all the saved claims show up :+1:

**Comment by eorodrig** [comment]
Local persistance works!

Same calls as network persistance

**Comment by eorodrig** [comment]
Synchronized Async load tasks with main task.

Feel free to play with it with the app and provide feedback.

At log-in:
the user is searched in the network
if found, claims are loaded with a synchronous task
Semaphore is released once task is done.

In the main loop:
Operations freeze after call to load claims is done (Looks for a semaphore)
Once semaphore is released, it changes activity to claim List.
